
# Proyecto VI. Análisis exploratorio de datos (EDA)
## Mundial de Fútbol 2026

### 1. Introducción

El objetivo de este proyecto es realizar un análisis exploratorio del conjunto de datos relacionado con el Mundial de Fútbol de 2026.

A través de Python y sus principales librerías de análisis de datos, se estudiará la estructura del dataset, la calidad de los datos, la presencia de valores ausentes y duplicados, y las características de las variables.

Posteriormente, se aplicarán técnicas de limpieza y transformación y se elaborarán visualizaciones que permitan identificar patrones y extraer conclusiones relevantes.

### 2. Herramientas utilizadas

- **Pandas y NumPy:** exploración, transformación y análisis de datos.
- **Matplotlib y Seaborn:** visualización gráfica.
- **Jupyter Notebook:** documentación y ejecución del análisis.
- **Git y GitHub:** control de versiones y documentación del proyecto.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Localizar la raíz del repositorio
RAIZ = (
    Path.cwd().parent
    if Path.cwd().name.lower() == "notebooks"
    else Path.cwd()
)

# Cargar el dataset
RUTA_DATOS = RAIZ / "data" / "Data_Mundial_2026.csv"
df = pd.read_csv(RUTA_DATOS)

# Primera inspección
print("Dimensiones del dataset:", df.shape)
display(df.head())

Dimensiones del dataset: (104, 42)

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1.0,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2.0,0.0,...,11,3,1,12,8,8,7,1.0,1.0,NaN
1,Group stage,1.0,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2.0,1.0,...,16,4,5,12,15,11,7,2.0,2.0,NaN
2,Group stage,1.0,Fri,2026-06-12,15:00,Canada,Bosnia–Herz,1–1,1.0,1.0,...,20,9,4,24,10,4,10,1.0,0.0,NaN
3,Group stage,1.0,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4.0,1.0,...,17,3,1,17,5,11,9,2.0,1.0,NaN
4,Group stage,1.0,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1.0,1.0,...,11,3,10,8,35,10,7,0.0,1.0,NaN

In [16]:

# Información general del dataset
print("Dimensiones:", df.shape)

print("\nInformación de las columnas:")
df.info()

print("\nTipos de datos:")
display(df.dtypes)

Dimensiones: (104, 42)

Información de las columnas:
<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   round               104 non-null    str
 1   gameweek            72 non-null     float64
 2   dayofweek           104 non-null    str
 3   date                104 non-null    datetime64[us]
 4   start_time          104 non-null    str
 5   home_team           104 non-null    str
 6   away_team           104 non-null    str
 7   score               104 non-null    str
 8   home_score          100 non-null    float64
 9   away_score          100 non-null    float64
 10  attendance          104 non-null    str
 11  venue               104 non-null    str
 12  referee             104 non-null    str
 13  home_formation      104 non-null    str
 14  away_formation      104 non-null    str
 15  home_manager        104 non-null    str
 16  away_manager        104 non-null    str
 17  home_captain        104 non-null    str
 18  away_captain        104 non-null    str
 19  home_possession     104 non-null    int64
 20  away_possession     104 non-null    int64
 21  home_sot            104 non-null    int64
 22  away_sot            104 non-null    int64
 23  home_total_shots    104 non-null    int64
 24  away_total_shots    104 non-null    int64
 25  home_saves          104 non-null    int64
 26  away_saves          104 non-null    int64
 27  home_cards_yellow   104 non-null    int64
 28  away_cards_yellow   104 non-null    int64
 29  home_cards_red      104 non-null    int64
 30  away_cards_red      104 non-null    int64
 31  home_fouls          104 non-null    int64
 32  away_fouls          104 non-null    int64
 33  home_corners        104 non-null    int64
 34  away_corners        104 non-null    int64
 35  home_crosses        104 non-null    int64
 36  away_crosses        104 non-null    int64
 37  home_interceptions  104 non-null    int64
 38  away_interceptions  104 non-null    int64
 39  home_offsides       99 non-null     float64
 40  away_offsides       99 non-null     float64
 41  notes               9 non-null      str
dtypes: datetime64[us](1), float64(5), int64(20), str(16)
memory usage: 34.3 KB

Tipos de datos:

round                            str
gameweek                     float64
dayofweek                        str
date                  datetime64[us]
start_time                       str
home_team                        str
away_team                        str
score                            str
home_score                   float64
away_score                   float64
attendance                       str
venue                            str
referee                          str
home_formation                   str
away_formation                   str
home_manager                     str
away_manager                     str
home_captain                     str
away_captain                     str
home_possession                int64
away_possession                int64
home_sot                       int64
away_sot                       int64
home_total_shots               int64
away_total_shots               int64
home_saves                     int64
away_saves                     int64
home_cards_yellow              int64
away_cards_yellow              int64
home_cards_red                 int64
away_cards_red                 int64
home_fouls                     int64
away_fouls                     int64
home_corners                   int64
away_corners                   int64
home_crosses                   int64
away_crosses                   int64
home_interceptions             int64
away_interceptions             int64
home_offsides                float64
away_offsides                float64
notes                            str
dtype: object

In [5]:
print(df.isnull().sum())

round                  0
gameweek              32
dayofweek              0
date                   0
start_time             0
home_team              0
away_team              0
score                  0
home_score             4
away_score             4
attendance             0
venue                  0
referee                0
home_formation         0
away_formation         0
home_manager           0
away_manager           0
home_captain           0
away_captain           0
home_possession        0
away_possession        0
home_sot               0
away_sot               0
home_total_shots       0
away_total_shots       0
home_saves             0
away_saves             0
home_cards_yellow      0
away_cards_yellow      0
home_cards_red         0
away_cards_red         0
home_fouls             0
away_fouls             0
home_corners           0
away_corners           0
home_crosses           0
away_crosses           0
home_interceptions     0
away_interceptions     0
home_offsides          5
away_offsides          5
notes                 95
dtype: int64

In [6]:
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

display(df.head())

Filas: 104
Columnas: 42

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1.0,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2.0,0.0,...,11,3,1,12,8,8,7,1.0,1.0,NaN
1,Group stage,1.0,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2.0,1.0,...,16,4,5,12,15,11,7,2.0,2.0,NaN
2,Group stage,1.0,Fri,2026-06-12,15:00,Canada,Bosnia–Herz,1–1,1.0,1.0,...,20,9,4,24,10,4,10,1.0,0.0,NaN
3,Group stage,1.0,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4.0,1.0,...,17,3,1,17,5,11,9,2.0,1.0,NaN
4,Group stage,1.0,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1.0,1.0,...,11,3,10,8,35,10,7,0.0,1.0,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   round               104 non-null    str
 1   gameweek            72 non-null     float64
 2   dayofweek           104 non-null    str
 3   date                104 non-null    str
 4   start_time          104 non-null    str
 5   home_team           104 non-null    str
 6   away_team           104 non-null    str
 7   score               104 non-null    str
 8   home_score          100 non-null    float64
 9   away_score          100 non-null    float64
 10  attendance          104 non-null    str
 11  venue               104 non-null    str
 12  referee             104 non-null    str
 13  home_formation      104 non-null    str
 14  away_formation      104 non-null    str
 15  home_manager        104 non-null    str
 16  away_manager        104 non-null    str
 17  home_captain        104 non-null    str
 18  away_captain        104 non-null    str
 19  home_possession     104 non-null    int64
 20  away_possession     104 non-null    int64
 21  home_sot            104 non-null    int64
 22  away_sot            104 non-null    int64
 23  home_total_shots    104 non-null    int64
 24  away_total_shots    104 non-null    int64
 25  home_saves          104 non-null    int64
 26  away_saves          104 non-null    int64
 27  home_cards_yellow   104 non-null    int64
 28  away_cards_yellow   104 non-null    int64
 29  home_cards_red      104 non-null    int64
 30  away_cards_red      104 non-null    int64
 31  home_fouls          104 non-null    int64
 32  away_fouls          104 non-null    int64
 33  home_corners        104 non-null    int64
 34  away_corners        104 non-null    int64
 35  home_crosses        104 non-null    int64
 36  away_crosses        104 non-null    int64
 37  home_interceptions  104 non-null    int64
 38  away_interceptions  104 non-null    int64
 39  home_offsides       99 non-null     float64
 40  away_offsides       99 non-null     float64
 41  notes               9 non-null      str
dtypes: float64(5), int64(20), str(17)
memory usage: 34.3 KB

In [8]:
nulos = pd.DataFrame({
    "valores_nulos": df.isnull().sum(),
    "porcentaje_nulos": (df.isnull().mean() * 100).round(2)
})

display(nulos[nulos["valores_nulos"] > 0]
        .sort_values("porcentaje_nulos", ascending=False))

               valores_nulos  porcentaje_nulos
notes                     95             91.35
gameweek                  32             30.77
away_offsides              5              4.81
home_offsides              5              4.81
home_score                 4              3.85
away_score                 4              3.85

In [9]:
print("Filas completamente duplicadas:", df.duplicated().sum())

Filas completamente duplicadas: 0

In [10]:
# Convertir la fecha al formato datetime
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

# Revisar las fechas que no se hayan podido interpretar
print("Fechas no válidas:", df["date"].isna().sum())

# Inspeccionar los valores originales de asistencia
display(df["attendance"].head(10))
print("Tipo de dato:", df["attendance"].dtype)

Fechas no válidas: 0

0    80,824
1    44,985
2    43,002
3    70,492
4    67,966
5    80,663
6    52,497
7    64,146
8    68,021
9    69,285
Name: attendance, dtype: str

Tipo de dato: str

In [11]:
df.dtypes

round                            str
gameweek                     float64
dayofweek                        str
date                  datetime64[us]
start_time                       str
home_team                        str
away_team                        str
score                            str
home_score                   float64
away_score                   float64
attendance                       str
venue                            str
referee                          str
home_formation                   str
away_formation                   str
home_manager                     str
away_manager                     str
home_captain                     str
away_captain                     str
home_possession                int64
away_possession                int64
home_sot                       int64
away_sot                       int64
home_total_shots               int64
away_total_shots               int64
home_saves                     int64
away_saves                     int64
home_cards_yellow              int64
away_cards_yellow              int64
home_cards_red                 int64
away_cards_red                 int64
home_fouls                     int64
away_fouls                     int64
home_corners                   int64
away_corners                   int64
home_crosses                   int64
away_crosses                   int64
home_interceptions             int64
away_interceptions             int64
home_offsides                float64
away_offsides                float64
notes                            str
dtype: object

In [12]:
display(df.describe().T)

,count,mean,min,25%,50%,75%,max,std
gameweek,72.0,2.0,1.0,1.0,2.0,3.0,3.0,0.822226
date,104,2026-06-24 18:00:00,2026-06-11 00:00:00,2026-06-18 00:00:00,2026-06-24 00:00:00,2026-06-30 00:00:00,2026-07-19 00:00:00,NaN
home_score,100.0,1.76,0.0,1.0,1.0,3.0,7.0,1.518372
away_score,100.0,1.26,0.0,0.0,1.0,2.0,6.0,1.25223
home_possession,104.0,52.423077,24.0,43.0,52.5,62.0,79.0,13.101317
away_possession,104.0,47.701923,21.0,38.0,47.5,57.0,76.0,13.093302
home_sot,104.0,4.846154,0.0,2.0,4.0,7.0,15.0,3.108926
away_sot,104.0,3.673077,0.0,2.0,3.0,5.0,11.0,2.502202
home_total_shots,104.0,14.019231,2.0,8.75,13.0,19.0,32.0,6.42202
away_total_shots,104.0,10.769231,2.0,7.0,10.0,14.0,35.0,5.846301
home_saves,104.0,2.403846,0.0,1.0,2.0,3.0,9.0,1.913261
away_saves,104.0,3.125,0.0,1.75,3.0,4.0,15.0,2.510899
home_cards_yellow,104.0,1.153846,0.0,0.0,1.0,2.0,4.0,1.021794
away_cards_yellow,104.0,1.509615,0.0,1.0,1.0,2.0,7.0,1.343775
home_cards_red,104.0,0.038462,0.0,0.0,0.0,0.0,1.0,0.193239
away_cards_red,104.0,0.105769,0.0,0.0,0.0,0.0,2.0,0.366518
home_fouls,104.0,11.625,3.0,9.0,11.0,13.25,24.0,4.027063
away_fouls,104.0,11.567308,1.0,8.0,12.0,14.0,25.0,4.403803
home_corners,104.0,5.182692,0.0,3.0,4.0,7.0,19.0,3.409764
away_corners,104.0,3.961538,0.0,2.0,4.0,5.0,14.0,2.661933
home_crosses,104.0,17.817308,4.0,11.75,15.0,22.0,56.0,10.338696
away_crosses,104.0,14.201923,1.0,9.0,13.0,18.0,47.0,7.325153
home_interceptions,104.0,8.086538,1.0,5.0,7.5,10.0,21.0,3.85945
away_interceptions,104.0,8.634615,3.0,6.0,8.5,11.0,16.0,3.128503
home_offsides,99.0,1.919192,0.0,1.0,2.0,3.0,8.0,1.523133
away_offsides,99.0,1.79798,0.0,1.0,1.0,3.0,6.0,1.597062

In [13]:
df_resultados = df.dropna(
    subset=["home_score", "away_score"]
).copy()

print("Partidos totales:", len(df))
print("Partidos con marcador:", len(df_resultados))

Partidos totales: 104
Partidos con marcador: 100

In [15]:
goles_totales = (
    df_resultados["home_score"].sum()
    + df_resultados["away_score"].sum()
)

media_goles = (
    goles_totales / len(df_resultados)
)

print("Goles totales:", goles_totales)
print(f"Media de goles por partido: {media_goles:.2f}")

Goles totales: 302.0
Media de goles por partido: 3.02